### ISSUE TITLE
Make it possible for people to change the net port

### ISSUE THREAD

**Issue by Brostosj** [plutoniumpw/plutonium-upnp#1]
some people have terrible routers and upnp cant work with two computers on the same network thats because of the netport

**Comment by RektInator** [comment]
> some people have terrible routers and upnp cant work with two computers on the same network thats because of the netport
If 1 port does not work, it tries to holepunch the next one. It attempts at max 25 ports to punch, if that does not work, UPnP is disabled. UPnP could also be disabled for other reasons, for example your network not being marked as private or your router not supporting the UPnP protocol the WinAPI uses.
